### ISSUE TITLE
Move JsonRpcClient to types and make public

### ISSUE THREAD

**Issue by jvliwanag** [ptol/typed-json-rpc#1]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Hoping to use `JsonRpcClient<T>` type directly. However it's private within `createJsonRpcClient`.

**Describe the solution you'd like**
Move `JsonRpcClient` to types and export from there.

## Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ptol** [comment]
Thanks for contribution
